# -*- coding: utf-8 -*-
"""LabActivity2_VELOSO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEqLCmhi_A5Q4C9dbEVbkCdjH8joIU9s
"""

class student():
    def __init__(self,name,age,gender,city,university,faculty,course,subintr1,subintr2,sprt):
        self.name = name
        self.age = age
        self.gender = gender
        self.city = city
        self.university = university
        self.faculty = faculty
        self.course = course
        self.subintr1 = subintr1
        self.subintr2 = subintr2
        self.sprt = sprt
    def student_background(self):
        print("Student name:", self.name)
        print("Current age:", self.age)
        print("Gender:", self.gender)
        print("Currently living in:", self.city)
    def student_university(self):
        print("Current university:", self.university)
        print("College derpartment:", self.faculty)
        print("Program or course:", self.course)
    def student_interest(self):
        print("My top subject interest is:", self.subintr1)
        print("My 2nd top subject interets is:", self.subintr2)
        print("My current and favorite sport:", self.sprt)
stud = student('Enrico Miguel Veloso',19,'Male','Marikina City','UST','College of Science','Data Science & Analytics','Math','Science','Volleyball')
stud.student_background()
stud.student_university()
stud.student_background()

print(" ")
class calculator():
    num1 = 0
    num2 = 0
    def addnum(self):
        s = self.num1 + self.num2
        print("Sum:",s)
    def subnum(self):
        d = self.num1 - self.num2
        print("Difference:",d)
    def mulnum(self):
        p = self.num1 * self.num2
        print("Product:",p)
    def divnum(self):
        q = self.num1 / self.num2
        print("Quotient:",q)
    def remnum(self):
        r = self.num1 % self.num2
        print("Remainder:",r)
calc = calculator()
calc.num1 = int(input("Enter 1st number:"))
calc.num2 = int(input("Enter 2nd number:"))
calc.addnum()
calc.subnum()
calc.mulnum()
calc.divnum()
calc.remnum()

print(" ")
class mathgame():
    gnum1 = 0
    def even(self):
        if self.gnum1 % 2 == 0:
            print("It is an even number")
        else:
            print("Not an even number")
    def odd(self):
        if self.gnum1 % 2 == 1:
            print("It is an odd number")
        else:
            print("Not an odd number")
    def divisble(self):
        if self.gnum1 % 5 == 0:
            print("It is divisible by 5")
        else:
            print("Not divisible by 5")
mg = mathgame()
mg.gnum1 = int(input("Enter any number:"))
mg.even()
mg.odd()
mg.divisble()

print(" ")
class grades:
    sub1 = 0
    sub2 = 0
    sub3 = 0
    sub4 = 0
    sub5 = 0
    sub6 = 0
    sub7 = 0
    def calculate_grade(self):
        print("Average:", (self.sub1 + self.sub2 + self.sub3 + self.sub4 + self.sub5 + self.sub6 + self.sub7) / 7)
    def highest_grade(self):
        list1 = []
        list1.append(self.sub1)
        list1.append(self.sub2)
        list1.append(self.sub3)
        list1.append(self.sub4)
        list1.append(self.sub5)
        list1.append(self.sub6)
        list1.append(self.sub7)
        print("Highest grade:",max(list1))
    def lowest_grade(self):
        list2 = []
        list2.append(self.sub1)
        list2.append(self.sub2)
        list2.append(self.sub3)
        list2.append(self.sub4)
        list2.append(self.sub5)
        list2.append(self.sub6)
        list2.append(self.sub7)
        print("lowest grade:",min(list2))
ave = grades()
ave.sub1 = int(input("Calculus#1 finals grade:"))
ave.sub2 = int(input("Discrete structures finals grade:"))
ave.sub3 = int(input("Intro to data science finals grade:"))
ave.sub4 = int(input("Fundamentals in programming finals grade:"))
ave.sub5 = int(input("Math in the modern world finals grade:"))
ave.sub6 = int(input("Theology 1 finals grade:"))
ave.sub7 = int(input("Path fit 1 finals grade:"))
ave.calculate_grade()
ave.highest_grade()
ave.lowest_grade()